apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "s3www.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - s3www.local
      secretName: s3www-tls
  rules:
    - host: s3www.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "s3www.name" . }}
                port:
                  number: 8080
    