apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3www.name" . }}
  namespace: up42
  labels:
    App: {{ include "s3www.name" . }}
spec:
  selector:
    App: {{ include "s3www.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.targetport }}
    