replicaCount: 1

image:
  repository: raviusit/s3www
  tag: 3.0.4
  pullPolicy: IfNotPresent

container:
  port: "8080"
  targetport: "8080"

args:
  - -bucket
  - s3www-static
  - -endpoint
  - http://minio-minio.up42.svc.cluster.local:9000

env:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  S3WWW_ADDRESS: 0.0.0.0:8080

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

monitoring:
  enabled: true
  interval: 60s
  prometheusRelease: prometheus
