apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.secret.accessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.secret.secretKey | b64enc }}
