apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "minio.name" . }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
