apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "minio.fullname" . }}-upload-cronjob
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-upload
              image: curlimages/curl
              command:
                - /bin/sh
                - -c
                - |
                  set -x

                  echo "Waiting for MinIO to be ready..."
                  until curl -s http://{{ include "minio.fullname" . }}:9000/minio/health/ready; do
                    echo "Still waiting..."
                    sleep 2
                  done

                  wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /tmp/mc && chmod +x /tmp/mc

                  /tmp/mc alias set local http://{{ include "minio.fullname" . }}:9000 {{ .Values.secret.accessKey }} {{ .Values.secret.secretKey }}
                  /tmp/mc mb --ignore-existing local/{{ .Values.bucketName }}

                  echo "Downloading and uploading images..."
                  {{- range $index, $url := .Values.imagesToDownload }}
                  curl -L -o /tmp/image{{$index}}.gif "{{ $url }}"
                  /tmp/mc cp /tmp/image{{$index}}.gif local/{{ $.Values.bucketName }}/image{{$index}}.gif
                  {{- end }}
